/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#e78e57",
        "background": "#faf9f6",
        "secondary-fixed-dim": "#c8c8b0",
        "error": "#ba1a1a",
        "secondary-container": "#e1e1c9",
        "tertiary-container": "#622a00",
        "inverse-primary": "#e1c1a4",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#1b1d0e",
        "surface-variant": "#e3e2e0",
        "primary-fixed": "#fedcbe",
        "on-secondary-fixed-variant": "#474836",
        "on-tertiary": "#ffffff",
        "surface-bright": "#faf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "tertiary-fixed": "#ffdbc9",
        "inverse-on-surface": "#f2f1ee",
        "on-surface-variant": "#4e453d",
        "tertiary": "#401900",
        "surface-container-highest": "#e3e2e0",
        "on-primary": "#ffffff",
        "secondary": "#5e604d",
        "primary-container": "#4b3621",
        "on-primary-fixed": "#291806",
        "surface": "#faf9f6",
        "on-surface": "#1a1c1a",
        "surface-dim": "#dbdad7",
        "surface-container-high": "#e9e8e5",
        "tertiary-fixed-dim": "#ffb68c",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#e1c1a4",
        "on-secondary-container": "#636451",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1a",
        "on-error": "#ffffff",
        "surface-tint": "#725a42",
        "on-primary-fixed-variant": "#59422c",
        "on-tertiary-fixed": "#321200",
        "primary": "#33210d",
        "outline": "#80756c",
        "inverse-surface": "#2f312f",
        "on-primary-container": "#bd9f83",
        "surface-container": "#efeeeb",
        "secondary-fixed": "#e4e4cc",
        "outline-variant": "#d2c4ba",
        "on-tertiary-fixed-variant": "#753401"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "max-width": "1280px",
        "gutter": "24px",
        "sm": "12px",
        "md": "24px",
        "base": "8px",
        "xl": "80px",
        "lg": "48px",
        "xs": "4px",
        "margin-mobile": "16px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "display-lg-mobile": ["Playfair Display", "serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}